version: '2'

networks:
  default-network:
    driver: bridge

volumes:
  var-lib-sss:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /d/mercury/sss
 
services:
  ubuntu-sssd-ssh:
    image: ibpm/sssd:ubuntu-0.1
    networks:
      - default-network
    build:
      context: .
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    environment:
      - LDAP_URI=${LDAP_URI}
      - LDAP_USE_TSL=${LDAP_USE_TSL}
      - LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
      - LDAP_USER_SEARCH_BASE=${LDAP_USER_SEARCH_BASE}
      - LDAP_ACCESS_FILTER=${LDAP_ACCESS_FILTER}
      - LDAP_GROUP_SEARCH_BASE=${LDAP_GROUP_SEARCH_BASE}
      - LDAP_GROUP_MEMBER=${LDAP_GROUP_MEMBER}
      - LDAP_BIND_DN=${LDAP_BIND_DN}
      - LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD}
    volumes: 
      - var-lib-sss:/var/lib/sss:rw
    ports:
      - "8022:22"
      
