networks:
  default-network:
    driver: bridge

volumes:
  var-lib-sss:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /d/mercury/sss
  openldap:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /d/mercury/openldap	
  slapd-d:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /d/mercury/slapd.d 	  
 
services:
  openldap:
    image: ibpm/openldap:ubuntu-0.1
    hostname: openldap
    networks:
      - default-network
    environment:
      - LDAP_ORG_DC=${LDAP_ORG_DC}
      - LDAP_OLC_SUFFIX=${LDAP_OLC_SUFFIX}
      - LDAP_ROOT_CN=${LDAP_ROOT_CN}
      - LDAP_ROOT_DN=cn=${LDAP_ROOT_CN},${LDAP_OLC_SUFFIX}
      - LDAP_ROOT_PASSWD=${LDAP_ROOT_PASSWD}
      - LDAP_TECHNICAL_USER_CN=${LDAP_TECHNICAL_USER_CN}
      - LDAP_TECHNICAL_USER_PASSWD=${LDAP_TECHNICAL_USER_PASSWD}
      - LDAP_OLC_ACCESS=${LDAP_OLC_ACCESS:-by * read}
      - SERVER_DEBUG=${SERVER_DEBUG:-0}
    volumes: 
      - openldap:/var/lib/ldap:rw
      - slapd-d:/etc/ldap/slapd.d:rw
#
# We do not expose ports from the container. LDAP access only via UI
# The ldap-ui application needs access to * for anonymous, hence exposing
# LDAP ports is not desirable.
#      
# Nie wystawiamy portów z kontenera. Dostęp do LDAP tylko za posrednictwem UI
# Apliakcja ldap-ui potrzebuje dostępu do * dla anonymous, stąd wystawianie 
# portów LDAP nie jest porządane.
#    ports:
#      - "389:389"
#      - "636:636"     
  ubuntu-sssd-ssh:
    image: ibpm/sssd:ubuntu-0.1
    hostname: ubuntu-sssd-ssh
    networks:
      - default-network
    build:
      context: .
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    depends_on:
      - openldap	  
    environment:
      - LDAP_URI=${LDAP_URI:-ldap://openldap:389}
      - LDAP_USE_TSL=${LDAP_USE_TSL:-false}
      - LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
      - LDAP_USER_SEARCH_BASE=${LDAP_USER_SEARCH_BASE}
      - LDAP_ACCESS_FILTER=${LDAP_ACCESS_FILTER}
      - LDAP_GROUP_SEARCH_BASE=${LDAP_GROUP_SEARCH_BASE}
      - LDAP_GROUP_MEMBER=${LDAP_GROUP_MEMBER:-uniqueMember}
      - LDAP_BIND_DN=${LDAP_BIND_DN}
      - LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD}
    volumes: 
      - var-lib-sss:/var/lib/sss:rw
    ports:
      - "8022:22"
  ldap-ui:
    image: dnknth/ldap-ui
    build: .
    hostname: ldap-ui
    networks:
      - default-network
    depends_on:
      - openldap	  
    links:
      - openldap	  
    environment:
      - LDAP_URL=${LDAP_URI:-ldap://openldap:389}/
      - USE_TLS=${UI_USE_TLS:-}
      - INSECURE_TLS=${UI_INSECURE_TLS:-}
      - BASE_DN=${LDAP_SEARCH_BASE}
#
# Authentication transferred to the application using the BASIC method.
# You provide the name (uid) of the ldapui user and its password
#      
# Uwierzytelnianie przeniesione do aplikacji metodą BASIC.
# Podajesz nazwe (uid) użytkownika ldapui i jego hasło
#      - BIND_DN=${UI_BIND_DN}
#      - BIND_PASSWORD=${UI_BIND_PASSWORD}     
    ports:
      - "5000:5000"
